# Generated by Django 3.0.7 on 2020-06-19 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
