# Generated by Django 3.0.7 on 2020-06-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_buy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Product'),
        ),
    ]
