# Generated by Django 3.0.7 on 2020-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200619_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
