# Generated by Django 3.0.7 on 2020-07-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_buy_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='update',
        ),
    ]
