# Generated by Django 3.0.7 on 2020-08-17 17:12

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_buy_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='totalamount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
