# Generated by Django 3.0.7 on 2020-08-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_buy_totalamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='totalamount',
        ),
    ]
